companyName: "Elektro-Tel AG"
phone: "0800 800 813"
email: "info@elektro-tel.ch"
whatsapp: "+41763145553"
footerText: "Ihr kompetenter Partner für sämtliche Elektro- und Telekommunikationsinstallationen. Von der Planung über die Installation bis zum Unterhalt stehen wir Ihnen mit unserem Fachwissen zur Seite."
socialLinks:
  facebook: "https://www.facebook.com/people/Elektro-Tel-AG/100063451046079/#"
  instagram: "https://www.instagram.com/elektrotelag/"
  linkedin: "https://ch.linkedin.com/company/elektro-tel-ag"
locations:
  - name: "Winterthur"
    street: "Rudolf-Diesel-Strasse 25"
    city: "8404 Winterthur"
    mapsUrl: "https://maps.app.goo.gl/mzRwwEr7hxoQzgyu8"
  - name: "Tägerwilen"
    street: "Bahnhofstrasse 17"
    city: "8274 Tägerwilen"
    mapsUrl: "https://maps.app.goo.gl/A8hcsziffBQM8r219"
  - name: "Schaffhausen"
    street: "Solenbergstrasse 35"
    city: "8207 Schaffhausen"
    mapsUrl: "https://goo.gl/maps/Schaffhausen"
